### ISSUE TITLE
Tests pass when running `rails test test:system` but don't when using `git push` or in GitHub CI

### ISSUE THREAD

**Issue by crmne** [crmne/cluster-headache-tracker#67]
**Describe the bug**
When running `rails test test:system` tests pass successfully, but not when using `git push`, which fires up the tests via `overcommit`, or in GitHub CI.

**To Reproduce**

1. `git push`

**Expected behavior**
Tests passing.

**Screenshots**
![failures_test_visiting_the_index](https://github.com/user-attachments/assets/f2ae3611-9627-491d-b2b4-4753bb918e55)
![failures_test_marking_ongoing_headache_as_complete](https://github.com/user-attachments/assets/a71b813a-057e-461e-b0c1-e1acb5e471c4)
![failures_test_generating_and_copying_share_link](https://github.com/user-attachments/assets/00714b21-ca44-4e0c-98f4-adb56a4ad9a3)
![failures_test_filtering_headache_logs](https://github.com/user-attachments/assets/3e44579d-1d23-4594-8c03-468079458d8e)
![failures_test_creating_a_new_headache_log](https://github.com/user-attachments/assets/0e22f68d-2d44-405e-a1e6-a3b096ac6425)
![failures_test_filtering_chart_data](https://github.com/user-attachments/assets/18a179d6-af66-46a1-90b6-44d5c14c5a29)
![failures_test_charts_show_no_data_message_when_filtered_with_no_results](https://github.com/user-attachments/assets/0a7aff4a-a4ee-4c4d-9b2f-67443a98bc50)

**Desktop (please complete the following information):**

- OS: Fedora Linux 41
- Browser: Firefox

**Additional context**
GitHub CI logs: https://github.com/crmne/cluster-headache-tracker/actions/runs/11583716798/job/32249432330

These are the git push logs:

```
$ git push
Running pre-push hooks
Check for security vulnerabilities.........................[Brakeman] OK
Upload files tracked by Git LFS..............................[GitLfs] OK
Run Minitest test suite....................................[Minitest] FAILED
Running 42 tests in a single process (parallelization threshold is 50)
Run options: --seed 47316

# Running:

........Capybara starting Puma...
* Version 6.4.3, codename: The Eagle of Durango
* Min threads: 0, max threads: 4
* Listening on http://127.0.0.1:40851
[Screenshot Image]: /home/carmine/Code/Personal/cluster-headache-tracker/tmp/screenshots/failures_test_charts_show_no_data_message_when_filtered_with_no_results.png
E

Error:
ChartsTest#test_charts_show_no_data_message_when_filtered_with_no_results:
Capybara::ElementNotFound: Unable to find visible link or button "Filters"
    test/system/charts_test.rb:35:in `block in <class:ChartsTest>'

bin/rails test test/system/charts_test.rb:33

[Screenshot Image]: /home/carmine/Code/Personal/cluster-headache-tracker/tmp/screenshots/failures_test_filtering_chart_data.png
E

Error:
ChartsTest#test_filtering_chart_data:
Capybara::ElementNotFound: Unable to find visible link or button "Filters"
    test/system/charts_test.rb:22:in `block in <class:ChartsTest>'

bin/rails test test/system/charts_test.rb:20

.....[Screenshot Image]: /home/carmine/Code/Personal/cluster-headache-tracker/tmp/screenshots/failures_test_creating_a_new_headache_log.png
E

Error:
HeadacheLogsTest#test_creating_a_new_headache_log:
Capybara::ElementNotFound: Unable to find field "Start time" that is not disabled
    test/system/headache_logs_test.rb:22:in `block in <class:HeadacheLogsTest>'

bin/rails test test/system/headache_logs_test.rb:18

.[Screenshot Image]: /home/carmine/Code/Personal/cluster-headache-tracker/tmp/screenshots/failures_test_filtering_headache_logs.png
E

Error:
HeadacheLogsTest#test_filtering_headache_logs:
Capybara::ElementNotFound: Unable to find visible link or button "Filters"
    test/system/headache_logs_test.rb:64:in `block in <class:HeadacheLogsTest>'

bin/rails test test/system/headache_logs_test.rb:62

[Screenshot Image]: /home/carmine/Code/Personal/cluster-headache-tracker/tmp/screenshots/failures_test_generating_and_copying_share_link.png
E

Error:
HeadacheLogsTest#test_generating_and_copying_share_link:
Capybara::ElementNotFound: Unable to find link or button "Share with Healthcare Provider"
    test/system/headache_logs_test.rb:77:in `block in <class:HeadacheLogsTest>'

bin/rails test test/system/headache_logs_test.rb:75

[Screenshot Image]: /home/carmine/Code/Personal/cluster-headache-tracker/tmp/screenshots/failures_test_marking_ongoing_headache_as_complete.png
E

Error:
HeadacheLogsTest#test_marking_ongoing_headache_as_complete:
Capybara::ElementNotFound: Unable to find field "End time" that is not disabled
    test/system/headache_logs_test.rb:55:in `block in <class:HeadacheLogsTest>'

bin/rails test test/system/headache_logs_test.rb:47

.[Screenshot Image]: /home/carmine/Code/Personal/cluster-headache-tracker/tmp/screenshots/failures_test_visiting_the_index.png
F

Failure:
HeadacheLogsTest#test_visiting_the_index [test/system/headache_logs_test.rb:13]:
expected to find css "h1" but there were no matches

bin/rails test test/system/headache_logs_test.rb:11

....................

Finished in 23.409421s, 1.7941 runs/s, 3.3747 assertions/s.
42 runs, 79 assertions, 1 failures, 6 errors, 0 skips
DEPRECATION WARNING: `to_time` will always preserve the full timezone rather than offset of the receiver in Rails 8.0. To opt in to the new behavior, set `config.active_support.to_time_preserves_timezone = :zone`. (called from <top (required)> at /home/carmine/Code/Personal/cluster-headache-tracker/config/environment.rb:5)
DEPRECATION WARNING: `to_time` will always preserve the full timezone rather than offset of the receiver in Rails 8.0. To opt in to the new behavior, set `config.active_support.to_time_preserves_timezone = :zone`. (called from <top (required)> at /home/carmine/Code/Personal/cluster-headache-tracker/config/environment.rb:5)


✗ One or more pre-push hooks failed

error: failed to push some refs to 'github.com:crmne/cluster-headache-tracker.git'
```

**Comment by PhilTee** [comment]
Still trying to get my local env set up to run (Rails 8, nice!)

I'm looking at your `test/system/headache_logs_test.rb` file, and at the `fill_in` method calls on lines 22 and 55
I think `fill_in` is case-sensitive, so it is looking for "Start time" and "End time", when the screen shots have an uppercase T in Time for both fields.

I'll see if I can confirm once my old clunky MacBook has finished updating rbenv and installing Ruby 3.3.5

**Comment by PhilTee** [comment]
Yeah, I've got `test/system/headache_logs_test.rb` passing now.
I don't think I have permissions to push up a branch though.
I'll call it a day for now, as it's almost 1AM here 😴 

```
```

**Comment by crmne** [comment]
Hi @PhilTee thank you so much for the fix!

In order to push a fix you need to make a PR, which will enable you to get credit for your work since your name will be associated with the commit, and will enable me to do a code review. Here's the step by step guide:

1. Fork this repo
2. Push the fix in your repos main branch
3. Open a PR to this repo

**Comment by PhilTee** [comment]
PR submitted for this issue here: https://github.com/crmne/cluster-headache-tracker/pull/69

All tests passing within the PR, including the system tests.
`fill_in` issue resolved
added helper method to `ApplicationSystemTestCase` allowing Capybara to open accordions

Logic of one test has had to be changed in the `generating and copying share link` test.
The user already had a share link, so when the modal is opened the **Generate New Link** button is displayed instead of the **Generate Share Link** button.  Hope that's ok.

**Comment by crmne** [comment]
Great work @PhilTee !

**Comment by PhilTee** [comment]
> Great work @PhilTee !

Thanks! Anything else I can take a look at?

**Comment by crmne** [comment]
> Thanks! Anything else I can take a look at?

Thank _you_! There's this issue about a new feature that would introduce separate [medication tracking](https://github.com/crmne/cluster-headache-tracker/issues/9) from headache tracking. The concept is not fully fleshed out, and the UI would need to be thought about more in depth, but happy to have discussions on the other issue about it!
